### ISSUE TITLE
Runtime errro in parallel mode

### ISSUE THREAD

**Issue by yuntongzhang** [nus-apr/cerberus#122]
When running cerberus in parallel mode (command used: `cerberus --task-type repair --tool=fuzzrepair --benchmark=vulnloc --bug-index-list=1-8,11-43 -g --cpu-count=103 --runs=10 --tool-param="--rand-patch-seed"`), the following runtime error occurred in the middle of the run:

![image](https://github.com/nus-apr/cerberus/assets/16000056/e9607e20-a895-4541-aae3-44165afe259e)

For more information, I was running around 410 tasks in total for this run. When this runtime error occurred, 348 of them have finished.

**Comment by Marti2203** [comment]
I found the bug - the lock API was being misused and there was the risk of race conditions - fixed in 641bcac3
