### ISSUE TITLE
Paralllel Mode with --rebuild-all or --rebuild-base

### ISSUE THREAD

**Issue by yuntongzhang** [nus-apr/cerberus#123]
When doing `-rebuild-all` with parallel mode, cerberus may terminate before actually running all the experiments. For example, I was performing a run with 410 experiments in total, in parallel mode, but cerberus terminated much earlier than expected, and left 348 experiments with summary file N/A.

The command that triggered this behavior was: `cerberus --task-type repair --tool=fuzzrepair --benchmark=vulnloc --bug-index-list=1-8,11-43 -g --cpu-count=90 --runs=10 --tool-param="--no-patch-evolution" --rebuild-all`. When the command did not include `--rebuild-all`, cerberus could finish all the experiments last time.

**Comment by Marti2203** [comment]
I think this comes up due to the docker daemon timing out while building with a lot of subjects to build, I have increased the timeout to 15 mins in eb6facfd3
