### ISSUE TITLE
Questions about APR-Comp setup

### ISSUE THREAD

**Issue by andre15silva** [nus-apr/cerberus#127]
Hi,

I'm trying to integrate a tool intro cerberus for the APR Competition, but am facing a few questions that don't seem obvious to me, and for which I don't find an answer on the README:

1. I was informed that fault localization has to be handled by the tools. However, the `bug_info` dictionary contains perfect fault-localization information (keys: `source_file`, `line_numbers`). Do I need to run with a special setting to hide this info, or have the rules changed?
2. What are the Java versions are we expected to run?
3. What benchmarks are we expected to support? Are the build scripts the original ones (for each benchmark), or do you provide custom ones? If so, how can my driver access them? It would be nice to have this kind of information easily accessible.

PS: 
I am using the code on https://github.com/nus-apr/cerberus/pull/114
Running the following command:
```bash
cerberus -task repair --bug-index 1 --benchmark=defects4j --tool=repairllama
```

**Comment by Marti2203** [comment]
Hi @andre15silva ,

For Java, an example benchmark of the vulnerability track is at the APR-comp profile, [shortcut link](https://github.com/APR-Comp/vulnerabilities-java/blob/main/meta-data.json). This will be the format that has to be supported. Now to answer all the questions.

1) Yes, the Defects4j benchmark contains perfect fault localization, but that one is not part of the competition.

The `bug_info` dictionary is only provided to the tool driver. Therefore if you do not use it, nothing is presented to the tool running in the container.

2) For Java versions - Java 8 is the required support. The example benchmark confirms this.

3) The benchmarks that we expect your tool to support are the ones in the [APR-COMP profile](https://github.com/orgs/APR-Comp/repositories). All tracks in the APR-COMP will have the same information in the `bug_info` dict. The important fields which allow you to be interoperable across benchmarks are  "build_script", "config_script", "test_script" , which provide a unified format across languages and tooling.  We do not customize the original build scripts, we provide an abstraction over the different scripts.

**Comment by andre15silva** [comment]
Thanks a lot @Marti2203!

Quick question: what paths should I consider in the diff output?

Will absolute paths work or should they be relative to something?

**Comment by Marti2203** [comment]
Hi @andre15silva ,
No problem :) Preferably using paths, relative from the root of the project will make things easier to compare across tooling.
