### ISSUE TITLE
The APRCompAIJava driver does not compile tests

### ISSUE THREAD

**Issue by xmcp** [nus-apr/cerberus#128]
Currently this driver [runs `mvn compile -DskipTests`](https://github.com/nus-apr/cerberus/blob/dev/app/drivers/benchmarks/java/APRCompAIJava.py#L48) during setup, and thus it does not create the `target/test-classes` directory [as mentioned in the meta-data.json](https://github.com/APR-Comp/autocode-java/blob/main/meta-data.json#L9).

It should call the `build_subject` script instead, which will hopefully create that directory.

**Comment by Marti2203** [comment]
Hi, pushed a fix for the driver in commit d1c7d2c3 on dev. This will generate the directory
