### ISSUE TITLE
line_numbers for APR competition

### ISSUE THREAD

**Issue by WuYff** [nus-apr/cerberus#129]
Hello,
We are participating in the APR competition. For functional error Java, we notice there is no line_numbers entry in meta_data.json. For AI generated code Python track, the line_numbers is empty in meta_data.json in the demo benchmark. Will the line_number be provided as perfect fault localization for APR tools?

**Comment by Marti2203** [comment]
Hi,
We do not provide perfect fault localization lines in the benchmarks. The task of localizing the faults is left to the tools
