### ISSUE TITLE
Missing Track on EasyChair

### ISSUE THREAD

**Issue by andre15silva** [nus-apr/cerberus#135]
Hi,

We just submitted our paper.

However, we did not find the "AI Generated Code (Java)" track on the EasyChair platform.
Is this a bug?

We signed up for these instead:
> AI Generated Code - JavaScript, Functional Errors - Java

**Comment by Marti2203** [comment]
Hi @andre15silva  
I don't think this is the right place for this question but I can answer that it is probably a bug on Easy Chair - the AI code Javascript track should be replaced by AI code Java :sweat_smile:  Will delegate this issue
