### ISSUE TITLE
missing line_numbers for aprcompvulnc dataset in subtrack vulnerability C/C++ repair

### ISSUE THREAD

**Issue by qadong** [nus-apr/cerberus#143]
In some samples from 'aprcompvulnc', we noticed the absence of 'line_numbers'. We would like to clarify that if this is consistent across the entire competition dataset. Moreover, when using localization tools like 'vulnloc' to pinpoint vulnerabilities, we observed that a 1-hour timeout may perhaps be inadequate for 'vulnloc' to determine accurate vulnerability locations.

**Comment by rshariffdeen** [comment]
@qadong during the competition no localization information will be provided, the tools must find the fix locations
