### ISSUE TITLE
Compilation of Bears and Bugs.jar

### ISSUE THREAD

**Issue by jose** [nus-apr/cerberus#157]
Hi @nus-apr,

In the context of another project, I've been struggling to compile bugs directly from the [Bears benchmark](https://github.com/bears-bugs/bears-benchmark) and from the [Bugs.jar benchmark](https://github.com/bugs-dot-jar/bugs-dot-jar), mostly because nonessential build steps (e.g., license checks by [Apache RAT](https://creadur.apache.org/rat/) or documentation generation by Javadoc) fail.

I've just looked at your [`Bears.py`](https://github.com/nus-apr/cerberus/blob/master/app/drivers/benchmarks/java/Bears.py#L70) and [`BugsDotJar.py`](https://github.com/nus-apr/cerberus/blob/master/app/drivers/benchmarks/java/BugsDotJar.py#L66), and it seems that you compile/build bugs with just

```bash
mvn compile -DskipTests
```

Is Cerberus really able to successfully compile **all** bugs from those two benchmarks? (I'm aware that support to the [Bugs.jar benchmark](https://github.com/bugs-dot-jar/bugs-dot-jar) [is not yet fully implemented](https://github.com/nus-apr/cerberus/blob/master/app/drivers/benchmarks/java/BugsDotJar.py#L8).)

So far, the best set of maven flags that have allowed me to compile most (if not all) bugs is:

```bash
mvn clean install -DskipTests -DskipUTs=true -DskipITs=true \
  -V -B -U -Dhttps.protocols=TLSv1.2 \
  -Denforcer.skip=true \
  -Dcheckstyle.skip=true \
  -Dcobertura.skip=true \
  -Djacoco.skip=true \
  -Drat.skip=true \
  -Drat.ignoreErrors=true \
  -Drat.numUnapprovedLicenses=1000000 \
  -Dlicense.skip=true \
  -Dfindbugs.skip=true \
  -Dgpg.skip=true \
  -Dskip.npm=true \
  -Dskip.gulp=true \
  -Dskip.bower=true \
  -Dbaseline.skip=true \
  -Dmaven.javadoc.skip=true
```

**Comment by Marti2203** [comment]
Hi @jose,
Both benchmarks are in an experimental state with less support for Bugs.jar. It is known that Bears [has some issues with reproducability](https://github.com/bears-bugs/bears-benchmark/issues/332). Furthermore, increasing support for the benchmarks is on our roadmap but is not a priority now. If you think your project can benefit from integrating with Cerberus, we are happy to merge a PR :smile: to help the community. :smile:
