### ISSUE TITLE
Arja_E driver does not support TP2

### ISSUE THREAD

**Issue by Hzxin** [nus-apr/cerberus#186]
### [composite-workflows] Arja_e driver does not support for TP2. 

1. In Task.py
```
if config_info[definitions.KEY_CONFIG_FIX_LOC] == "tool":
        if definitions.KEY_LOCALIZATION in experiment_info:
            del experiment_info[definitions.KEY_LOCALIZATION]
```

When TP2 is specified, the localization key from bug_info is removed.
In Arja_e driver, line 88-90, the deleted key_localization was accessed, causing key error in TP2 setting.
```
        localization_lines = self.transform_localization(
            bug_info[self.key_localization]
        )
```

**Comment by Marti2203** [comment]
Fixed in dabb730b45
