### ISSUE TITLE
Ensure that Cerberus uses the latest image for a tool

### ISSUE THREAD

**Issue by Marti2203** [nus-apr/cerberus#20]
This has caused some headaches.

**Comment by rshariffdeen** [comment]
@Marti2203 can you add more details to this issue?

**Comment by Marti2203** [comment]
We do not automatically rebuild subject images, whenever the tool image is updated. This is currently manually done with the user passing ``--rebuild-all`` but it would be better if we automatically catch it. I already have an idea how to do it, so will try doing it in the next week.

**Comment by Marti2203** [comment]
Finally fixed it in dev.
