### ISSUE TITLE
Console prints not visible on certain light terminal background.

### ISSUE THREAD

**Issue by yuntongzhang** [nus-apr/cerberus#36]
When running on command line, because of the color of the output text, some of them are not visible when the terminal background is light.

For example, here is the output when solarized light background is used.

![image](https://user-images.githubusercontent.com/16000056/226514595-d9496fac-4041-4227-8271-5644bd83644a.png)

**Comment by Marti2203** [comment]
This is not a problem with the new TUI but will keep it open for now.

**Comment by rshariffdeen** [comment]
@Marti2203 even in TUI it is a problem, the color codes we use are specific not system references. 
@yuntongzhang feel free to send a PR if you have a solution.

**Comment by Marti2203** [comment]
The TUI colors are made to be system independent, so I cannot make them depend on the system ones but I can make the colors be better suited for different versions.

**Comment by rshariffdeen** [comment]
In that case, we can have two set of color sets one for dark mode and one for light mode?

**Comment by Marti2203** [comment]
There should be something that helps with that. I have to look into it in the next days

**Comment by Marti2203** [comment]
Currently I have updated this for the TUI, will be looking into it for the console

**Comment by Marti2203** [comment]
Figured out a solution for the console and the TUI. Latest dev commit supports it.
