### ISSUE TITLE
Unable to build benchmark environment

### ISSUE THREAD

**Issue by LouisSY** [nus-apr/cerberus#38]
Hi,

I tried to to run  `cerberus --tool=f1x --benchmark=manybugs --bug-index=1` I got the following message:

====================================================================================================

	Starting Cerberus (Program Repair Framework) 
====================================================================================================

	Bootstrapping framework
	__________________________________________________________________________________________

	reading profile values
	reading configuration values from arguments
	updating configuration values
		[config] depth: 3
		[config] iteration-limit: 1
		[config] patch-rank-limit: 5
		[config] stack-size: 15000
		[config] use-cache: False
		[config] use-gpu: False
		[config] use-container: True
		[config] email-setup: False
		[config] is-debug: True
		[config] use-purge: False
		[config] only-analyse: False
		[config] only-setup: False
		[config] rebuild-all: False
		[config] rebuild-base: False
		[config] subject-name: None
		[config] benchmark-name: manybugs
		[config] dump-patches: False
		[config] start-index: None
		[config] end-index: None
		[config] bug-id-list: []
		[config] bug-index-list: [1]
		[config] skip-index-list: []
		[config] tool-list: ['f1x']
		[config] directories: {'data': '/data'}
		[config] profile-id-list: ['C1']

	Initializing setup
	__________________________________________________________________________________________

	loading repair tool
			[debug]      using tool: f1x
	loading benchmark
		[benchmark] benchmark environment not found
		[benchmark] building benchmark environment
			[benchmark] building docker image
	Repair Failed
	[error] Unable to build image: Dockerfile not found
	Runtime Error
	Error. Exiting...
	
Run time statistics:
-----------------------

	Experiment Count: -1

It seems that it cannot find the dockerfile of Manybugs???

I'm using the latest version of cerberus, and my system is Ubuntu22.04.

By the way, when I tried to pull cerberrus from github with `git clone --recurse-submodules https://github.com/nus-apr/cerberus`, I got the following error:

```
fatal: clone of 'git@github.com:nus-apr/pulse-benchmark.git' into submodule path '/cerberus/benchmark/pulse' failed
Failed to clone 'benchmark/pulse' a second time, aborting
```
Will this error message causes the error above? `[error] Unable to build image: Dockerfile not found`

Thank you so much!!!

**Comment by rshariffdeen** [comment]
Hi,
Some of the benchmarks are still under preparation so they are privately hosted, for your experiment you can run 
`git submodule update --init --remote benchmark/manybugs` which would clone the submodule.

**Comment by LouisSY** [comment]
I have tried this method but it still doesn't work.

====================================================================================================

	Starting Cerberus (Program Repair Framework) 
====================================================================================================


	Bootstrapping framework
	__________________________________________________________________________________________

	reading profile values
	reading configuration values from arguments
	updating configuration values
		[config] depth: 3
		[config] iteration-limit: 1
		[config] patch-rank-limit: 5
		[config] stack-size: 15000
		[config] use-cache: False
		[config] use-gpu: False
		[config] use-container: True
		[config] email-setup: False
		[config] is-debug: False
		[config] use-purge: False
		[config] only-analyse: False
		[config] only-setup: False
		[config] rebuild-all: False
		[config] rebuild-base: False
		[config] subject-name: None
		[config] benchmark-name: manybugs
		[config] dump-patches: False
		[config] start-index: None
		[config] end-index: None
		[config] bug-id-list: []
		[config] bug-index-list: [1]
		[config] skip-index-list: []
		[config] tool-list: ['f1x']
		[config] directories: {'data': '/data'}
		[config] profile-id-list: ['C1']

	Initializing setup
	__________________________________________________________________________________________

	loading repair tool
	[warning] docker image not found in Docker registry
	pulling docker image
	loading benchmark
		[benchmark] benchmark environment not found
		[benchmark] building benchmark environment
			[benchmark] building docker image
	Repair Failed
	[error] Unable to build image: Dockerfile not found
	Runtime Error
	Error. Exiting...
	
Run time statistics:
-----------------------

	Experiment Count: -1
	
Cerberus exited with an error after 1.625 minutes

**Comment by Marti2203** [comment]
Can you run it in debug mode?

**Comment by rshariffdeen** [comment]
I was able to run from my end, can you check if your submodule has correctly checkout the benchmark at `benchmark/manybugs` it should contain the Dockerfile in the directory.

**Comment by Marti2203** [comment]
It is empty because we have started using git submodules to make the cerberus repository smaller and easier to pull

**Comment by LouisSY** [comment]
May I ask how to figure this out???  I have tried `git submodule init`, `git submodule update`, `git submodule update --init --recursive` or `git submodule update --init --remote benchmark/manybugs` but these commands are not helpful

**Comment by Marti2203** [comment]
> How figure this out?

You mean fix it?
I have a suspicion that the git submodule URLs I have created do not work properly as they are ssh-based and I thought it is safer but alas... I would suggest changing the URL in `.gitmodules` and `.git/config` from `url = git@github.com:nus-apr/manybugs.git`
to `url = https://github.com@nus-apr/manybugs.git` and then trying to do the update

**Comment by Marti2203** [comment]
No problem :) I am pretty sure that the moment the submodules work properly all should be well

**Comment by rshariffdeen** [comment]
@LouisSY were you abel to resolve the issue? I have created a new issue for cerberus to automatically make the updates for the submodules when needed in https://github.com/nus-apr/cerberus/issues/48

**Comment by Marti2203** [comment]
I am going to close this as there have been a lot of updates and the submodules issue should be fixed
