### ISSUE TITLE
Error handling for the docker image creation process

### ISSUE THREAD

**Issue by shark4ce** [nus-apr/cerberus#42]
The error handling for the docker image creation process is not implemented properly. There is no info/warnings about when and why a docker image could not be created. However, the tool crashes when it tries to create a docker container from a docker image that does not exist.

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/46487296/228729527-b04e2ea5-4a9b-48a8-a1be-348964556642.png">

**Comment by Marti2203** [comment]
Possibly fixed in dev. Need to try to reproduce it
