### ISSUE TITLE
Log file names are not readable and the main log files can be overwritten

### ISSUE THREAD

**Issue by crhf** [nus-apr/cerberus#50]
A log file in logs/ uses timestamp as its name, which makes it awkward to find out which experiment the log is for.

Also, logs/log-build, logs/log-command, etc. can be overwritten by a later experiment.

**Comment by rshariffdeen** [comment]
Thanks for creating an issue, the hash appended as a postfix is to enable multiple runs without overriding previous results. Perhaps a better approach is to enable/disable the hashing, can be done using a user argument than making it default.

**Comment by Marti2203** [comment]
This issue is a little stale, so I will close it.
We have changed the format name of the logs to make it more readable (`log_month_date_hour_min`). Regarding the overwriting, this should be less of a problem with the support of parallel execution.
