### ISSUE TITLE
`results` contains empty dirs and tarballs

### ISSUE THREAD

**Issue by crhf** [nus-apr/cerberus#60]
```
$ tree results
results
├── C5-arja_e-defects4j-Lang-61-d29edc0e
└── arja_e
    └── C5-arja_e-defects4j-Lang-61-d29edc0e.tar.gz
```

where `results/C5-arja_e-defects4j-Lang-61-d29edc0e` is empty. This looks quite weired. Is this intended? I would expect something that is directly readable.

**Comment by Marti2203** [comment]
Hi, Now by default the artifacts will not be deleted. I fixed it in #65
