### ISSUE TITLE
Missing import in SequenceR.py

### ISSUE THREAD

**Issue by thanhlecongg** [nus-apr/cerberus#62]
Hi, 

I'm attempting to use sequenceR with Cerberus, but it do not import the definitions (from app.core) in the file SequenceR.py located at in app/drivers/tools/repair/java/SequenceR.py, causing the following error: "NameError: name 'definitions' is not defined".

**Comment by Marti2203** [comment]
Hi, which branch are you using?

**Comment by thanhlecongg** [comment]
I'm using master branch.
