### ISSUE TITLE
Stable version for Cerberus 

### ISSUE THREAD

**Issue by thanhlecongg** [nus-apr/cerberus#66]
Hi,

Thank you very much for providing such a useful tool. It has greatly helped me in my work. I am currently using Cerberus to run a learning-based repair tool. However, while using the master and dev branches, I encountered several bugs and issues.

As I understand that Cerberus is still under development, I am aware that encountering issues is inevitable. However, I would greatly appreciate it if you could provide me with an older version of Cerberus with a commit hash that is known to be more stable.

Thank you.

**Comment by Marti2203** [comment]
Hi,
Generally we are striving now to have the master branch being stable but sometimes some interactions may slip during testing. If there is a bug do open an issue and we can look into it.

**Comment by thanhlecongg** [comment]
Thanks, I will try to work on master branch.
