### ISSUE TITLE
Outdated code of SequenceR contains bug. 

### ISSUE THREAD

**Issue by thanhlecongg** [nus-apr/cerberus#70]
Hi, 

When running Cerberus with SequenceR, I face a bug that make Cerberus ignore repair scripts in Chart-13 in Defects4J dataset.
```
                (debug) Tokenizing the abstraction
                (debug) Count not find buggy line ('// ONLY FOR TOKENIZATION, BUGGY LINE BELOW' missing)
                (debug) Tokenization failed
```

After checking, I found that the bug is actually come from sequenceR instead of Cerberus. The bug have been already fixed by this [commit](https://github.com/ASSERT-KTH/sequencer/commit/a42d4aebb418fdcd6723912f1cce9ed82dde1ae8). However, the code in the docker is outdated, leading to bug happening in Cerberus. I wonder if you could review the commit and make an update in the SequenceR docker image to avoid  the bugs and potential bias in evaluating SequenceR. 

Many thanks.

**Comment by Marti2203** [comment]
Hi, I see that the commit is from January. We had added SequenceR to Cerberus before that. It is possible to change it as it is mostly recompilling the image.  I can set something up next week for it. Thanks for the notification!

**Comment by thanhlecongg** [comment]
Yes, thank you so much.

**Comment by thanhlecongg** [comment]
I wrongly closed the issues. May be you can close it when the problem is solved.

**Comment by Marti2203** [comment]
Yep, just finished. The latest version of SequenceR is used in the dev branch
