### ISSUE TITLE
Runtime Error 'max_usage'

### ISSUE THREAD

**Issue by LouisSY** [nus-apr/cerberus#72]
Hi, thank you so much for developing such a useful tool! It works really well but  sometimes when I run cerberus, it gives such an error:

                        [benchmark][manybugs] deploy failed

                        Runtime Error

                        'max_usage'

May I ask if this is normal or there might be something wrong with my installation?
An example command for me to meet this error: `cerberus repair --tool f1x --benchmark=manybugs --bug-index=11`

**Comment by Marti2203** [comment]
Hi, if this is on master - this is a known bug fixed on dev. The reason is that apparently the results of docker are inconsistent.
In stats.py you can replace the definition of `self.mem_usage_gb` with this one
```
        self.mem_usage_gb = round(
            container_stats["memory_stats"].get(
                "max_usage", container_stats["memory_stats"].get("usage", 0)
            )
            / (1024 * 1024 * 1024),
            3,
        )
```
