### ISSUE TITLE
Missing line_numbers in Defects4J meta-data.json

### ISSUE THREAD

**Issue by thanhlecongg** [nus-apr/cerberus#73]
Hi, 
I recently observed that many data in meta-data.json has empty line numbers. I assume the line numbers are perfect fault localization which are necessary to run APR tools .  I wonder if this is intentional and we should fill it later? Or you plan to integrate fault localization as a part of Cerberus. Many thanks.

**Comment by Marti2203** [comment]
Hi,
The lines which have information were taken from other tools (SequenceR mostly, this relates to issue #23  ). If somebody has information about the faulty lines, it would be nice to integrate it and yes, adding Fault Localization is on the roadmap.

**Comment by thanhlecongg** [comment]
Hi @Marti2203, I have extracted perfect fault localization for Defects4J. The information could be found here. 
https://drive.google.com/file/d/1xJslU2o9jv1t2TzPkf4tCjiO8nMgQ5HF/view?usp=sharing

The json file have the following structure:
```
{
"1": { // bug ID following your metadata files
        "subject": "Chart", // Defects4J subject
        "bug_id": 1, // Defects4J bug ID
        "locations": { 
            "org/jfree/chart/renderer/category/AbstractCategoryItemRenderer.java": [ // buggy methods
                1797
            ] // list of buggy lines
        }
    },
}

The information is extracted based on [scripts](https://bitbucket.org/rjust/fault-localization-data/src/master/d4j_integration/get_buggy_lines.sh) provided by authors of Defects4J. 

I planned to integrate it into your metadata files. However, I found that the current format in your meta data file does not support bugs with multiple classes so please help me to integrate it. Thanks. 
```

**Comment by rshariffdeen** [comment]
Hi @thanhlecongg ,

thanks for looking into it, our current implementation needs some modification to handle multiple fault locations, once this is done we can seek your help to integrate the information for Defects4J.
