### ISSUE TITLE
support quick iteration when developing a repair strategy

### ISSUE THREAD

**Issue by andre15silva** [nus-apr/cerberus#74]
It would be nice to be able to quickly iterate over an in-development repair strategy, without needing to build too many things (e.g. docker images), so that we can quickly evaluate new ideas.

**Comment by rshariffdeen** [comment]
We do support local deployment, using `--local`

This assumes the environment is setup to run the repair tool.

**Comment by andre15silva** [comment]
Hi @rshariffdeen!

I added this issue following a discussion with @Marti2203, where he said that there might be some issue with accessing the benchmarks. Maybe he can explain better what the issue would be.

**Comment by rshariffdeen** [comment]
Hi @andre15silva ,
in-development repair techniques can be used in two ways, 
1. deploying and testing on local machine, can be used with ``--local`` flag which expects the invocation can be executed (i.e. system paths are configured if using aliases)
2. locally built docker image exist for tool, specifying the local image name in the driver is sufficient

let me know if this helps, or you are looking for a different setup?

**Comment by Marti2203** [comment]
Hi @andre15silva , I have developed an implementation of the discussed idea in commit b8256eba  - there is a folder called `dynamic` where your tool can be stored, this allows you to quickly update your codebase and not have to rebuild the containers.
