### ISSUE TITLE
How to run a specific Defects4J bug?

### ISSUE THREAD

**Issue by andre15silva** [nus-apr/cerberus#79]
How can I set cerberus to run on a specific Defects4J bug?

If I set the `--bug-id` option to `Chart-1`, `Chart1` or even `Chart/1` it does not find any bug with that identifier.
On the other hand, if I set `--bug-id` to `1`, it runs on all bugs with `bid==1` (i.e., `Chart-1`, `Cli-1`, `Csv-1`, etc)

```bash
cerberus repair --tool=sequencer --benchmark=defects4j --bug-id Chart-1 # does not find any bug
cerberus repair --tool=sequencer --benchmark=defects4j --bug-id 1 # runs on all bugs with bid==1
```

**Comment by Marti2203** [comment]
Hi, this is a fault on the side of the metadata provided. You are using the command correctly

**Comment by rshariffdeen** [comment]
Hi @andre15silva, 
thanks for reporting the issue, it seems there are two bugs
one in the meta-data of the benchmark configuration and the other in Cerberus filtering mechanism 

@Marti2203 is it possible to update the meta-data or do we need to handle it in the driver?

**Comment by Marti2203** [comment]
It is possible to update the meta-data fle.

**Comment by Marti2203** [comment]
Hi, just updated the benchmark repo we use and dev is fixed
