### ISSUE TITLE
Hardcoding in Recoder

### ISSUE THREAD

**Issue by thanhlecongg** [nus-apr/cerberus#82]
I have found that Recoder seem to be hardcoded, which presents a difficulty in repairing bugs without a GPU and utilizing the meta-data from meta-data.json. If you intend to address these issues, I can submit a pull request and docker image that enables Recoder to function properly with Defects4J.

**Comment by Marti2203** [comment]
Hi Thanh Le-Cong, yes, that would be quite nice to have. Just to give a heads up please do record how much RAM was needed to Recoder over a CPU just so it is documented in the driver

**Comment by thanhlecongg** [comment]
Noted. I will provide the information along with pull request.

**Comment by Marti2203** [comment]
Thank you! :) Your help is much appreciated

**Comment by thanhlecongg** [comment]
@Marti2203 Btw, which branch should I make a pull request? Is it dev?

**Comment by Marti2203** [comment]
Yes

**Comment by thanhlecongg** [comment]
Done in pull request #83
