### ISSUE TITLE
Sometimes it is not desirable to pull new tool images

### ISSUE THREAD

**Issue by yuntongzhang** [nus-apr/cerberus#85]
In a repair tool development environment, sometimes I build a new docker image after making some changes to the tool, and then run Cerberus to test the tool on some benchmark.

However, the current Cerberus behavior is to always pull an image, even if an image is available locally. Since it is time consuming to push every test image of tool to docker hub, the remote image may be outdated in such a development workflow. The current behavior of Cerberus would then force to use the (remote) older image instead, but the desired behavior is to use the (local) new image.

**Comment by rshariffdeen** [comment]
thanks for reporting the issue, I have fixed the workflow in 5b9c96a to only pull the latest when a certain flag is provided at runtime, default behaviour would be to use the local image.
