### ISSUE TITLE
Buggy location for Lang-40 is wrong

### ISSUE THREAD

**Issue by thanhlecongg** [nus-apr/cerberus#89]
Hi, 

I found that the buggy location for the Lang-40 bug in the Defects4J benchmark is wrong. The correct line should be 1048  (instead of 223 in the current version) according to [Defects4J-dissection](http://program-repair.org/defects4j-dissection/#!/bug/Lang/40)

**Comment by Marti2203** [comment]
Hi @thanhlecongg ,
This is interesting. The data for the fault localization was taken from SequenceR, so I will have to update the benchmark repository and the submodule reference. Thanks for the info! :) Will put it as an issue on the other repository
