### ISSUE TITLE
Runtime error when running in UI mode

### ISSUE THREAD

**Issue by yuntongzhang** [nus-apr/cerberus#91]
I was using cerberus in UI mode to run multiple repair tasks in parallel. However, there was the following runtime error after a while:

![image](https://github.com/nus-apr/cerberus/assets/16000056/dce10491-45f0-4296-b379-ca905600fb01)

The command used: `cerberus --task-type repair --tool=fuzzrepair --benchmark=vulnloc --rebuild-all --bug-index-list=1-8,11-43 -g --cpu-count=18`

**Comment by Marti2203** [comment]
Added a patch for this situation in 74826942
