### ISSUE TITLE
Runtime error: 'networks'

### ISSUE THREAD

**Issue by dylanjwolff** [nus-apr/cerberus#97]
Hi guys,

I've been trying to get the fuzzing microbenchmark setup working, but I'm getting a runtime error from Cerberus immediately when I run it. 

command: 
```bin/cerberus --benchmark=microfuzz --tool=studentfuzzer --task fuzz```

```
Runtime Error
'networks'

Run time statistics:
-----------------------

Experiment Count: 1

 Cerberus exited with an error after 0.067 minutes
 ```
 
 logfiles:
[log-error.txt](https://github.com/nus-apr/cerberus/files/12208778/log-error.txt)
[log-Jul_30_16_31.txt](https://github.com/nus-apr/cerberus/files/12208779/log-Jul_30_16_31.txt)
[log-command.txt](https://github.com/nus-apr/cerberus/files/12208780/log-command.txt)

I can share the microbench directory privately if needed @rshariffdeen -- @Marti2203 already has it

**Comment by rshariffdeen** [comment]
probably a version issue with the `docker` library @Marti2203 ?

**Comment by rshariffdeen** [comment]
@dylanjwolff thanks for reporting the issue, yes I would need the benchmark to reproduce this error

**Comment by dylanjwolff** [comment]
@rshariffdeen it's in the private repo I shared with you guys a few weeks ago: "fuzzing-comp-assignment"

**Comment by Marti2203** [comment]
@dylanjwolff , @rshariffdeen yes, this is surely an issue with the python `docker` SDK version as I have ran this without issues. I will add a patch to not assume that such statistics always exist

**Comment by Marti2203** [comment]
commit 955cc1d5 on dev fixes this error

**Comment by dylanjwolff** [comment]
confirmed fixed! thanks!

Fyi docker version was 24.0.2 (API version 1.43)
